baseURL = "https://nateluzod.github.io/nate-is/"
languageCode = "en-us"
title = "Nate Luzod"
theme = "hyde"
publishDir = "../docs"

[params]
  description = "Developer/Designer hybrid in Honolulu, Hawaii"
  author = "Nate Luzod"